-- MySQL Script generated by MySQL Workbench
-- Tue May 30 17:57:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
  `` INT NOT NULL,
  PRIMARY KEY (``))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table3` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table4` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouse` (
  `Warehouse_BID` INT NOT NULL,
  `Warehouse_ItemID` VARCHAR(45) NULL,
  PRIMARY KEY (`Warehouse_BID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Request` (
  `Request_ID` INT(10) NOT NULL,
  `Request_BID` INT(10) NOT NULL,
  `Request_CreateDate` DATE NULL,
  PRIMARY KEY (`Request_ID`));


-- -----------------------------------------------------
-- Table `mydb`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Branch` (
  `Branch_ID` INT NOT NULL,
  `Branch_Address` VARCHAR(45) NULL,
  `Branch_Telephone` VARCHAR(45) NULL,
  `Warehouse_Warehouse_BID` INT NOT NULL,
  `Request_Request_ID` INT(10) NOT NULL,
  PRIMARY KEY (`Branch_ID`),
  INDEX `fk_Branch_Warehouse1_idx` (`Warehouse_Warehouse_BID` ASC) VISIBLE,
  INDEX `fk_Branch_Request1_idx` (`Request_Request_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Branch_Warehouse1`
    FOREIGN KEY (`Warehouse_Warehouse_BID`)
    REFERENCES `mydb`.`Warehouse` (`Warehouse_BID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Branch_Request1`
    FOREIGN KEY (`Request_Request_ID`)
    REFERENCES `mydb`.`Request` (`Request_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `Staff_ID` INT NOT NULL,
  `Staff_BranchID` VARCHAR(45) NULL,
  `Staff_JobTitle` VARCHAR(45) NULL,
  `Staff_Name` VARCHAR(45) NULL,
  `Staff_DOF` VARCHAR(45) NULL,
  `Staff_PhoneNumber` VARCHAR(45) NULL,
  `Branch_Branch_ID` INT NOT NULL,
  PRIMARY KEY (`Staff_ID`),
  INDEX `fk_Staff_Branch1_idx` (`Branch_Branch_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Staff_Branch1`
    FOREIGN KEY (`Branch_Branch_ID`)
    REFERENCES `mydb`.`Branch` (`Branch_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `Account` INT(10) NOT NULL,
  `Password` VARCHAR(20) NULL,
  `Staff_Staff_ID` INT NOT NULL,
  PRIMARY KEY (`Account`),
  INDEX `fk_LoginAccount_Staff_idx` (`Staff_Staff_ID` ASC) VISIBLE,
  CONSTRAINT `fk_LoginAccount_Staff`
    FOREIGN KEY (`Staff_Staff_ID`)
    REFERENCES `mydb`.`Staff` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Warehouse Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Warehouse Item` (
  `WI_ID` INT(10) NULL DEFAULT CURRENT_TIMESTAMP,
  `WI_Name` CHAR(30) NULL,
  `WI_Quantity` INT(10) NULL,
  `Warehouse_Warehouse_BID` INT NOT NULL,
  INDEX `fk_Warehouse Item_Warehouse1_idx` (`Warehouse_Warehouse_BID` ASC) VISIBLE,
  CONSTRAINT `fk_Warehouse Item_Warehouse1`
    FOREIGN KEY (`Warehouse_Warehouse_BID`)
    REFERENCES `mydb`.`Warehouse` (`Warehouse_BID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Request Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Request Item` (
  `Request_ID` INT(10) NOT NULL,
  `RI_ID` INT(10) NOT NULL,
  `RI_Quantity` INT(10) NULL,
  PRIMARY KEY (`Request_ID`));


-- -----------------------------------------------------
-- Table `mydb`.`Contract Purchase Agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contract Purchase Agreement` (
  `CPA_CID` INT(10) NOT NULL,
  `CPA_Effective Dates` DATE NOT NULL,
  PRIMARY KEY (`CPA_CID`));


-- -----------------------------------------------------
-- Table `mydb`.`Blanket Purchase Agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Blanket Purchase Agreement` (
  `BPA_AmountAgreed` INT(10) NOT NULL,
  `BPA_EffectiveDates` DATE NOT NULL,
  PRIMARY KEY (`BPA_AmountAgreed`));


-- -----------------------------------------------------
-- Table `mydb`.`Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Purchase` (
  `Purchase_EffectiveDate` DATE NOT NULL,
  `Purchase_CreateData` DATE NOT NULL,
  `Contract Purchase Agreement_CPA_CID` INT(10) NOT NULL,
  `Blanket Purchase Agreement_BPA_AmountAgreed` INT(10) NOT NULL,
  PRIMARY KEY (`Purchase_EffectiveDate`),
  INDEX `fk_Purchase_Contract Purchase Agreement1_idx` (`Contract Purchase Agreement_CPA_CID` ASC) VISIBLE,
  INDEX `fk_Purchase_Blanket Purchase Agreement1_idx` (`Blanket Purchase Agreement_BPA_AmountAgreed` ASC) VISIBLE,
  CONSTRAINT `fk_Purchase_Contract Purchase Agreement1`
    FOREIGN KEY (`Contract Purchase Agreement_CPA_CID`)
    REFERENCES `mydb`.`Contract Purchase Agreement` (`CPA_CID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Blanket Purchase Agreement1`
    FOREIGN KEY (`Blanket Purchase Agreement_BPA_AmountAgreed`)
    REFERENCES `mydb`.`Blanket Purchase Agreement` (`BPA_AmountAgreed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Despatch Instruction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Despatch Instruction` (
  `DI_RequestID` INT(10) NOT NULL,
  `DI_Destination` INT(10) NOT NULL,
  `DI_CreateDate` DATE NULL,
  `DI_EffectiveDate` DATE NULL,
  `Request_Request_ID` INT(10) NOT NULL,
  `Purchase_Purchase_EffectiveDate` DATE NOT NULL,
  PRIMARY KEY (`DI_RequestID`, `Request_Request_ID`, `Purchase_Purchase_EffectiveDate`),
  INDEX `fk_Despatch Instruction_Request1_idx` (`Request_Request_ID` ASC) VISIBLE,
  INDEX `fk_Despatch Instruction_Purchase1_idx` (`Purchase_Purchase_EffectiveDate` ASC) VISIBLE,
  CONSTRAINT `fk_Despatch Instruction_Request1`
    FOREIGN KEY (`Request_Request_ID`)
    REFERENCES `mydb`.`Request` (`Request_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Despatch Instruction_Purchase1`
    FOREIGN KEY (`Purchase_Purchase_EffectiveDate`)
    REFERENCES `mydb`.`Purchase` (`Purchase_EffectiveDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Despatch Instruction Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Despatch Instruction Item` (
  `DII_RequestID` INT(10) NOT NULL,
  `DII_ItemID` INT(10) NOT NULL,
  `DII_Quantity` INT(10) NULL,
  `Despatch Instruction_DI_RequestID` INT(10) NOT NULL,
  `Despatch Instruction_Request_Request_ID` INT(10) NOT NULL,
  `Despatch Instruction_Purchase_Purchase_EffectiveDate` DATE NOT NULL,
  PRIMARY KEY (`DII_RequestID`, `Despatch Instruction_DI_RequestID`, `Despatch Instruction_Request_Request_ID`, `Despatch Instruction_Purchase_Purchase_EffectiveDate`),
  INDEX `fk_Despatch Instruction Item_Despatch Instruction1_idx` (`Despatch Instruction_DI_RequestID` ASC, `Despatch Instruction_Request_Request_ID` ASC, `Despatch Instruction_Purchase_Purchase_EffectiveDate` ASC) VISIBLE,
  CONSTRAINT `fk_Despatch Instruction Item_Despatch Instruction1`
    FOREIGN KEY (`Despatch Instruction_DI_RequestID` , `Despatch Instruction_Request_Request_ID` , `Despatch Instruction_Purchase_Purchase_EffectiveDate`)
    REFERENCES `mydb`.`Despatch Instruction` (`DI_RequestID` , `Request_Request_ID` , `Purchase_Purchase_EffectiveDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Puchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Puchase` (
  `Purchase` INT(10) NOT NULL,
  `Contract Purchase Agreement` INT(10) NOT NULL,
  `Purchase_CreateDate` DATE NULL,
  PRIMARY KEY (`Purchase`));


-- -----------------------------------------------------
-- Table `mydb`.`Standard Purchase Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Standard Purchase Order` (
  `SPO_OrderID` INT(10) NOT NULL,
  `SPO_ShipmentAddress` CHAR(30) NOT NULL,
  `SPO_ExpectedDeliveryDate` DATE NOT NULL,
  `SPO_AmountAgreed` INT(15) NOT NULL,
  `Supplier_ID` INT(10) NOT NULL,
  `Blanket Purchase Agreement_BPA_AmountAgreed` INT(10) NOT NULL,
  PRIMARY KEY (`SPO_OrderID`),
  INDEX `fk_Standard Purchase Order_Blanket Purchase Agreement1_idx` (`Blanket Purchase Agreement_BPA_AmountAgreed` ASC) VISIBLE,
  CONSTRAINT `fk_Standard Purchase Order_Blanket Purchase Agreement1`
    FOREIGN KEY (`Blanket Purchase Agreement_BPA_AmountAgreed`)
    REFERENCES `mydb`.`Blanket Purchase Agreement` (`BPA_AmountAgreed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `Supplier_ID` INT(40) NOT NULL,
  `Supplier_Name` CHAR(40) NOT NULL,
  `Supplier_ContactPPL` CHAR(30) NOT NULL,
  `Supplier_ContactTel` INT(8) NOT NULL,
  `Supplier_Address` INT(10) NOT NULL,
  `Standard Purchase Order_SPO_OrderID` INT(10) NOT NULL,
  PRIMARY KEY (`Supplier_ID`),
  INDEX `fk_Supplier_Standard Purchase Order1_idx` (`Standard Purchase Order_SPO_OrderID` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_Standard Purchase Order1`
    FOREIGN KEY (`Standard Purchase Order_SPO_OrderID`)
    REFERENCES `mydb`.`Standard Purchase Order` (`SPO_OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Planned Purchase Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Planned Purchase Order` (
  `PPO_OrderID` INT(10) NOT NULL,
  `PPO_CID` DATE NOT NULL,
  `PPO_TentativeScheduled` CHAR(45) NOT NULL,
  `PPO_Amount` INT(15) NOT NULL,
  `Supplier_ID` INT(10) NOT NULL,
  `Contract Purchase Agreement_CPA_CID` INT(10) NOT NULL,
  `Supplier_Supplier_ID` INT(40) NOT NULL,
  PRIMARY KEY (`PPO_OrderID`),
  INDEX `fk_Planned Purchase Order_Contract Purchase Agreement1_idx` (`Contract Purchase Agreement_CPA_CID` ASC) VISIBLE,
  INDEX `fk_Planned Purchase Order_Supplier1_idx` (`Supplier_Supplier_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Planned Purchase Order_Contract Purchase Agreement1`
    FOREIGN KEY (`Contract Purchase Agreement_CPA_CID`)
    REFERENCES `mydb`.`Contract Purchase Agreement` (`CPA_CID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planned Purchase Order_Supplier1`
    FOREIGN KEY (`Supplier_Supplier_ID`)
    REFERENCES `mydb`.`Supplier` (`Supplier_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Order Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order Item` (
  `OI_OrderID` INT(10) NOT NULL,
  `OI_ID` INT(10) NOT NULL,
  `OI_Quantity` INT(10) NOT NULL,
  `Planned Purchase Order_PPO_OrderID` INT(10) NOT NULL,
  `Standard Purchase Order_SPO_OrderID` INT(10) NOT NULL,
  PRIMARY KEY (`OI_OrderID`, `Planned Purchase Order_PPO_OrderID`, `Standard Purchase Order_SPO_OrderID`),
  INDEX `fk_Order Item_Planned Purchase Order1_idx` (`Planned Purchase Order_PPO_OrderID` ASC) VISIBLE,
  INDEX `fk_Order Item_Standard Purchase Order1_idx` (`Standard Purchase Order_SPO_OrderID` ASC) VISIBLE,
  CONSTRAINT `fk_Order Item_Planned Purchase Order1`
    FOREIGN KEY (`Planned Purchase Order_PPO_OrderID`)
    REFERENCES `mydb`.`Planned Purchase Order` (`PPO_OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order Item_Standard Purchase Order1`
    FOREIGN KEY (`Standard Purchase Order_SPO_OrderID`)
    REFERENCES `mydb`.`Standard Purchase Order` (`SPO_OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `Item_ItemID` INT(40) NOT NULL,
  `Item_SupplierID` INT(40) NOT NULL,
  `Item_Name` VARCHAR(45) NOT NULL,
  `Item_PlaceOfProduction` INT(10) NOT NULL,
  PRIMARY KEY (`Item_ItemID`));


-- -----------------------------------------------------
-- Table `mydb`.`Request_has_Request Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Request_has_Request Item` (
  `Request_Request_ID` INT(10) NOT NULL,
  `Request Item_Request_ID` INT(10) NOT NULL,
  PRIMARY KEY (`Request_Request_ID`, `Request Item_Request_ID`),
  INDEX `fk_Request_has_Request Item_Request Item1_idx` (`Request Item_Request_ID` ASC) VISIBLE,
  INDEX `fk_Request_has_Request Item_Request1_idx` (`Request_Request_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Request_has_Request Item_Request1`
    FOREIGN KEY (`Request_Request_ID`)
    REFERENCES `mydb`.`Request` (`Request_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_has_Request Item_Request Item1`
    FOREIGN KEY (`Request Item_Request_ID`)
    REFERENCES `mydb`.`Request Item` (`Request_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
